Global:
  # QM9 dataset property: homo (HOMO energy, Hartree)
  label_names: ["homo"]
  do_train: True
  do_eval: False
  do_test: False

  graph_converter:
    __class_name__: CrystalNN
    __init_params__:
        num_cpus: 10

Trainer:
  max_epochs: 300
  seed: 42
  output_dir: ./output/spherenet_qm9_homo
  save_freq: 50
  log_freq: 20
  start_eval_epoch: 1
  eval_freq: 1
  pretrained_model_path: null
  pretrained_weight_name: null
  resume_from_checkpoint: null
  use_amp: False
  amp_level: 'O1'
  eval_with_no_grad: True
  gradient_accumulation_steps: 1

  best_metric_indicator: 'eval_metric'
  name_for_best_metric: "homo"
  greater_is_better: False

  compute_metric_during_train: True
  metric_strategy_during_eval: 'epoch'

  use_visualdl: False
  use_wandb: False
  use_tensorboard: False

Model:
  __class_name__: SphereNet
  __init_params__:
    out_channels: 1
    hidden_channels: 128
    num_blocks: 4
    int_emb_size: 64
    basis_emb_size_dist: 8
    basis_emb_size_angle: 8
    basis_emb_size_torsion: 8
    out_emb_channels: 256
    num_spherical: 7
    num_embeddings: 95
    num_radial: 6
    otf_graph: false
    cutoff: 5.0
    max_num_neighbors: 50
    envelope_exponent: 5
    num_before_skip: 1
    num_after_skip: 2
    num_output_layers: 3
    readout: sum
    property_names: ${Global.label_names}
    data_mean: 0.0
    data_std: 1.0
    loss_type: 'l1_loss'
    act: 'swish'
    output_init: 'GlorotOrthogonal'

Metric:
  homo:
    __class_name__: paddle.nn.L1Loss
    __init_params__: {}

Optimizer:
  __class_name__: Adam
  __init_params__:
    lr:
      __class_name__: Cosine
      __init_params__:
        learning_rate: 0.0005
        by_epoch: True

Dataset:
  split_dataset_ratio:
    train: 0.8
    val: 0.1
    test: 0.1
  dataset:
    __class_name__: QM9Dataset
    __init_params__:
      path: ./data/qm9
      property_names: ${Global.label_names}
      build_graph_cfg: ${Global.graph_converter}
      overwrite: False
      filter_unvalid: True
  loader:
    num_workers: 4
    use_shared_memory: False
    collate_fn: DefaultCollator
  train_sampler:
    __class_name__: BatchSampler
    __init_params__:
      shuffle: True
      drop_last: True
      batch_size: 32
  val_sampler:
    __class_name__: BatchSampler
    __init_params__:
      shuffle: False
      drop_last: False
      batch_size: 64

  transform:
    __class_name__: mean_std_scaling
    __init_params__: {}

Predict:
  graph_converter: ${Global.graph_converter}
  eval_with_no_grad: True
